#!/bin/bash

export GRISRED_DIR=`dirname $0`
echo grisred directory: $GRISRED_DIR

#show GIT information
cat $GRISRED_DIR/grisred.version

[ -z $FTSFILE ] && { export FTSFILE=$GRISRED_DIR/fts_combined.fits ;}
echo "FTSFILE="$FTSFILE

#IDL-setup
if [ -z $IDL_PATH ] ;then
    if [ -z $IDL_DIR ] ;then
        echo "setup IDL environment first." 
        exit
    else
        export IDL_PATH=+$IDL_DIR/lib
    fi
fi
    
export IDL_PATH=$GRISRED_DIR:$GRISRED_DIR/varlib:$IDL_PATH
DASH='==================================================================='
#create IDL startup file
INI=$GRISRED_DIR/grisini.pro
echo "print,'$DASH'" >$INI
echo "print,'GRIS data reduction routines'" >>$INI
echo "print,'$DASH'" >>$INI
echo "print,'Usage: '">>$INI
echo "print,'gris_v6, map, fileff, filecal, lambda=lambda, order=order [, /show]'">>$INI
echo "print,'$DASH'" >>$INI
#append an existing startup file
echo "device,true_color=24,decomposed=0,retain=2" >>$INI
echo $IDL_START
if [ ! -f $IDL_START ] ;then
    cat $IDL_START >> $INI
fi

export IDL_STARTUP=$INI
idl
